import { Listing } from './api';

export const DEMO_SALE_LISTINGS: Listing[] = [
  {
    id: '1',
    title: '[MẪU] Căn hộ 2PN view sông Sài Gòn, nội thất cao cấp',
    slug: 'ban-can-ho-2pn-view-song-sai-gon-id1',
    description: 'Căn hộ tầng trung thoáng mát, view trực diện sông, ban công rộng rãi đón gió tự nhiên. Bàn giao đầy đủ nội thất cao cấp: tủ bếp An Cường, thiết bị vệ sinh Kohler, sàn gỗ nhập khẩu. Tiện ích nội khu đầy đủ: hồ bơi vô cực, phòng gym hiện đại, khu vui chơi trẻ em, siêu thị 24/7. Pháp lý rõ ràng, sổ hồng lâu dài, ngân hàng hỗ trợ vay tối đa 70% giá trị căn hộ.',
    transactionType: 'sale',
    propertyType: 'can-ho',
    price: '3200000000',
    areaM2: '68.5',
    bedrooms: 2,
    bathrooms: 2,
    legalStatus: 'so_hong',
    addressDetail: 'Đường Nguyễn Lương Bằng, Phường Tân Phú, Quận 7, TP.HCM',
    status: 'active',
    publishedAt: new Date().toISOString(),
    viewCount: 142,
    images: [
      { imageUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&auto=format&fit=crop&q=80', sortOrder: 0 },
      { imageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&auto=format&fit=crop&q=80', sortOrder: 1 },
      { imageUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&auto=format&fit=crop&q=80', sortOrder: 2 },
      { imageUrl: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&auto=format&fit=crop&q=80', sortOrder: 3 },
    ],
    location: { id: 7, name: 'Quận 7, TP.HCM', slug: 'quan-7', level: 'district' },
    project: { id: '1', name: 'River Panorama', slug: 'river-panorama' },
    owner: { id: '2', fullName: 'Nguyễn Văn Nam (Môi giới)', avatarUrl: null, createdAt: '2026-01-15T00:00:00.000Z' },
  },
  {
    id: '2',
    title: '[MẪU] Nhà phố hiện đại mặt tiền đường nội bộ 12m',
    slug: 'ban-nha-pho-hien-dai-mat-tien-duong-12m-id2',
    description: 'Nhà 1 trệt 2 lầu đúc kiên cố, phong cách tân cổ điển sang trọng. Thiết kế thông minh với giếng trời thoáng sáng, phòng khách rộng rãi, gara xe hơi 7 chỗ vào tận nhà. Nằm trong khu dân cư kiểu mẫu an ninh 24/7, gần trường học quốc tế, bệnh viện và trung tâm thương mại. Sổ đỏ chính chủ, công chứng sang tên ngay.',
    transactionType: 'sale',
    propertyType: 'nha-nguyen-can',
    price: '6800000000',
    areaM2: '95',
    bedrooms: 4,
    bathrooms: 3,
    legalStatus: 'so_do',
    addressDetail: 'Khu dân cư An Phú, Phường An Phú, TP. Thủ Đức, TP.HCM',
    status: 'active',
    publishedAt: new Date().toISOString(),
    viewCount: 238,
    images: [
      { imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&auto=format&fit=crop&q=80', sortOrder: 0 },
      { imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80', sortOrder: 1 },
      { imageUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&auto=format&fit=crop&q=80', sortOrder: 2 },
    ],
    location: { id: 2, name: 'TP. Thủ Đức, TP.HCM', slug: 'tp-thu-duc', level: 'district' },
    project: null,
    owner: { id: '1', fullName: 'Trần Thị Mai', avatarUrl: null, createdAt: '2026-02-01T00:00:00.000Z' },
  },
];

export const DEMO_RENT_LISTINGS: Listing[] = [
  {
    id: '3',
    title: '[MẪU] Cho thuê căn hộ studio đầy đủ tiện nghi trung tâm',
    slug: 'cho-thue-can-ho-studio-day-du-tien-nghi-id3',
    description: 'Studio decor phong cách Scandinavian tối giản hiện đại, đầy đủ tiện nghi: giường nệm cao cấp, sofa, tivi smart 55 inch, tủ lạnh 2 cánh, máy giặt riêng, bếp từ và lò vi sóng. Ban công rộng ngắm toàn cảnh thành phố về đêm. Giờ giấc tự do, bảo vệ 24/24, thang máy thẻ từ, internet tốc độ cao miễn phí.',
    transactionType: 'rent',
    propertyType: 'can-ho',
    price: '9500000',
    areaM2: '35',
    bedrooms: 1,
    bathrooms: 1,
    legalStatus: 'hop_dong',
    addressDetail: 'Đường Nguyễn Thị Minh Khai, Phường Bến Nghé, Quận 1, TP.HCM',
    status: 'active',
    publishedAt: new Date().toISOString(),
    viewCount: 310,
    images: [
      { imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&auto=format&fit=crop&q=80', sortOrder: 0 },
      { imageUrl: 'https://images.unsplash.com/photo-1502005229762-ee1b2b93e083?w=800&auto=format&fit=crop&q=80', sortOrder: 1 },
    ],
    location: { id: 1, name: 'Quận 1, TP.HCM', slug: 'quan-1', level: 'district' },
    project: null,
    owner: { id: '2', fullName: 'Nguyễn Văn Nam (Môi giới)', avatarUrl: null, createdAt: '2026-01-15T00:00:00.000Z' },
  },
  {
    id: '4',
    title: '[MẪU] Mặt bằng kinh doanh tầng trệt phố thương mại',
    slug: 'cho-thue-mat-bang-kinh-doanh-tang-tret-id4',
    description: 'Vị trí đắc địa ngay tuyến phố kinh doanh sầm uất, mặt tiền rộng 6m thoáng đãng, vỉa hè 4m để xe thoải mái. Thích hợp kinh doanh cafe, showroom thời trang, văn phòng đại diện hoặc phòng khám nha khoa. Hệ thống điện 3 pha, cửa cuốn tự động, nhà vệ sinh riêng sạch sẽ. Hợp đồng dài hạn từ 2 năm trở lên.',
    transactionType: 'rent',
    propertyType: 'shophouse',
    price: '28000000',
    areaM2: '80',
    bedrooms: null,
    bathrooms: 1,
    legalStatus: 'hop_dong',
    addressDetail: 'Đường Hai Bà Trưng, Phường Võ Thị Sáu, Quận 3, TP.HCM',
    status: 'active',
    publishedAt: new Date().toISOString(),
    viewCount: 195,
    images: [
      { imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&auto=format&fit=crop&q=80', sortOrder: 0 },
      { imageUrl: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=800&auto=format&fit=crop&q=80', sortOrder: 1 },
    ],
    location: { id: 3, name: 'Quận 3, TP.HCM', slug: 'quan-3', level: 'district' },
    project: null,
    owner: { id: '1', fullName: 'Trần Thị Mai', avatarUrl: null, createdAt: '2026-02-01T00:00:00.000Z' },
  },
];

export const ALL_DEMO_LISTINGS: Listing[] = [...DEMO_SALE_LISTINGS, ...DEMO_RENT_LISTINGS];
