import { Listing } from './api';

export const DEMO_SALE_LISTINGS: Listing[] = [
  {
    id: '1',
    title: '[MẪU] Bán căn hộ 2PN view sông thoáng mát, sổ hồng chính chủ',
    slug: 'ban-can-ho-2pn-view-song-sai-gon-id1',
    description: 'Căn hộ tầng trung thoáng mát, view trực diện sông, ban công rộng rãi đón gió tự nhiên. Bàn giao đầy đủ nội thất cao cấp: tủ bếp, thiết bị vệ sinh cao cấp, sàn gỗ. Tiện ích nội khu đầy đủ: hồ bơi, phòng gym, siêu thị 24/7. Sổ hồng chính chủ, liên hệ trực tiếp anh Quân.',
    transactionType: 'sale',
    propertyType: 'can_ho',
    price: '3200000000',
    areaM2: '68.5',
    bedrooms: 2,
    bathrooms: 2,
    legalStatus: 'so_hong',
    addressDetail: 'Đường Nguyễn Lương Bằng, Quận 7, TP.HCM',
    status: 'active',
    publishedAt: new Date().toISOString(),
    viewCount: 142,
    images: [
      { imageUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&auto=format&fit=crop&q=75', sortOrder: 0 },
      { imageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&auto=format&fit=crop&q=70', sortOrder: 1 },
      { imageUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&auto=format&fit=crop&q=70', sortOrder: 2 },
    ],
    location: { id: 7, name: 'Quận 7, TP.HCM', slug: 'quan-7', level: 'district' },
    project: null,
    owner: { id: '1', fullName: 'Nguyễn Đức Quân (0981753082)', avatarUrl: null, createdAt: '2026-01-01T00:00:00.000Z' },
  },
  {
    id: '2',
    title: '[MẪU] Bán nhà phố hiện đại mặt tiền đường 12m, sổ đỏ trao tay',
    slug: 'ban-nha-pho-hien-dai-mat-tien-duong-12m-id2',
    description: 'Nhà 1 trệt 2 lầu đúc kiên cố, phong cách tân cổ điển sang trọng. Thiết kế thông minh với giếng trời thoáng sáng, phòng khách rộng rãi, gara xe hơi 7 chỗ vào tận nhà. Sổ đỏ chính chủ, công chứng sang tên ngay.',
    transactionType: 'sale',
    propertyType: 'nha_rieng',
    price: '6800000000',
    areaM2: '95',
    bedrooms: 4,
    bathrooms: 3,
    legalStatus: 'so_do',
    addressDetail: 'Khu dân cư An Phú, TP. Thủ Đức, TP.HCM',
    status: 'active',
    publishedAt: new Date().toISOString(),
    viewCount: 238,
    images: [
      { imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&auto=format&fit=crop&q=75', sortOrder: 0 },
      { imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&auto=format&fit=crop&q=70', sortOrder: 1 },
    ],
    location: { id: 2, name: 'TP. Thủ Đức, TP.HCM', slug: 'tp-thu-duc', level: 'district' },
    project: null,
    owner: { id: '1', fullName: 'Nguyễn Đức Quân (0981753082)', avatarUrl: null, createdAt: '2026-01-01T00:00:00.000Z' },
  },
];

export const DEMO_RENT_LISTINGS: Listing[] = [
  {
    id: '3',
    title: '[MẪU] Cho thuê phòng trọ khép kín full đồ, giờ giấc tự do',
    slug: 'cho-thue-phong-tro-khep-kin-full-do-id3',
    description: 'Phòng trọ khép kín sạch sẽ, trang bị sẵn điều hòa, nóng lạnh, gác lửng cao ráo. Giờ giấc tự do không chung chủ, có camera an ninh và khóa vân tay. Phù hợp sinh viên và người đi làm.',
    transactionType: 'rent',
    propertyType: 'phong_tro',
    price: '3500000',
    areaM2: '25',
    bedrooms: 1,
    bathrooms: 1,
    legalStatus: 'hop_dong',
    addressDetail: 'Ngõ 120 Đường Cầu Giấy, Hà Nội',
    status: 'active',
    publishedAt: new Date().toISOString(),
    viewCount: 310,
    images: [
      { imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&auto=format&fit=crop&q=75', sortOrder: 0 },
      { imageUrl: 'https://images.unsplash.com/photo-1502005229762-ee1b2b93e083?w=600&auto=format&fit=crop&q=70', sortOrder: 1 },
    ],
    location: { id: 1, name: 'Cầu Giấy, Hà Nội', slug: 'cau-giay', level: 'district' },
    project: null,
    owner: { id: '1', fullName: 'Nguyễn Đức Quân (0981753082)', avatarUrl: null, createdAt: '2026-01-01T00:00:00.000Z' },
  },
  {
    id: '4',
    title: '[MẪU] Cho thuê mặt bằng kinh doanh phố lớn, mặt tiền 6m',
    slug: 'cho-thue-mat-bang-kinh-doanh-pho-lon-id4',
    description: 'Vị trí đắc địa ngay tuyến phố sầm uất, mặt tiền rộng 6m thông thoáng, vỉa hè rộng để xe thoải mái. Thích hợp kinh doanh cafe, showroom, văn phòng, nha khoa. Hợp đồng dài hạn chính chủ.',
    transactionType: 'rent',
    propertyType: 'mat_bang',
    price: '25000000',
    areaM2: '70',
    bedrooms: null,
    bathrooms: 1,
    legalStatus: 'hop_dong',
    addressDetail: 'Mặt phố Nguyễn Trãi, Thanh Xuân, Hà Nội',
    status: 'active',
    publishedAt: new Date().toISOString(),
    viewCount: 195,
    images: [
      { imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&auto=format&fit=crop&q=75', sortOrder: 0 },
      { imageUrl: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=600&auto=format&fit=crop&q=70', sortOrder: 1 },
    ],
    location: { id: 3, name: 'Thanh Xuân, Hà Nội', slug: 'thanh-xuan', level: 'district' },
    project: null,
    owner: { id: '1', fullName: 'Nguyễn Đức Quân (0981753082)', avatarUrl: null, createdAt: '2026-01-01T00:00:00.000Z' },
  },
];

export const ALL_DEMO_LISTINGS: Listing[] = [...DEMO_SALE_LISTINGS, ...DEMO_RENT_LISTINGS];
