export interface UniversityData {
  slug: string;
  name: string;
  abbreviation: string;
  region: 'TP. Hồ Chí Minh' | 'Hà Nội' | 'Đà Nẵng & Miền Trung' | 'Cần Thơ & Miền Tây' | 'Miền Bắc khác';
  address: string;
  lat: number;
  lng: number;
}

export const VIETNAM_UNIVERSITIES: UniversityData[] = [
  // ── TP. HỒ CHÍ MINH ──
  {
    slug: 'dhqg-tphcm',
    name: 'Đại học Quốc gia TP.HCM (Khu Đô thị)',
    abbreviation: 'ĐHQG TP.HCM',
    region: 'TP. Hồ Chí Minh',
    address: 'Khu phố 6, P. Linh Trung, TP. Thủ Đức, TP.HCM',
    lat: 10.8753,
    lng: 106.8007,
  },
  {
    slug: 'dh-bach-khoa-tphcm',
    name: 'Trường Đại học Bách Khoa - ĐHQG TP.HCM',
    abbreviation: 'Bách Khoa HCM (HCMUT)',
    region: 'TP. Hồ Chí Minh',
    address: '268 Lý Thường Kiệt, Phường 14, Quận 10, TP.HCM',
    lat: 10.7726,
    lng: 106.6578,
  },
  {
    slug: 'dh-khoa-hoc-tu-nhien-tphcm',
    name: 'Trường Đại học Khoa học Tự nhiên - ĐHQG TP.HCM',
    abbreviation: 'KHTN TP.HCM (HCMUS)',
    region: 'TP. Hồ Chí Minh',
    address: '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP.HCM',
    lat: 10.7628,
    lng: 106.6825,
  },
  {
    slug: 'dh-khxh-nv-tphcm',
    name: 'Trường ĐH Khoa học Xã hội & Nhân văn - ĐHQG TP.HCM',
    abbreviation: 'KHXH&NV HCM (USSH)',
    region: 'TP. Hồ Chí Minh',
    address: '10-12 Đinh Tiên Hoàng, Bến Nghé, Quận 1, TP.HCM',
    lat: 10.7865,
    lng: 106.7018,
  },
  {
    slug: 'dh-kinh-te-luat-tphcm',
    name: 'Trường Đại học Kinh tế - Luật - ĐHQG TP.HCM',
    abbreviation: 'UEL',
    region: 'TP. Hồ Chí Minh',
    address: '669 QL1K, Linh Xuân, TP. Thủ Đức, TP.HCM',
    lat: 10.8756,
    lng: 106.7774,
  },
  {
    slug: 'dh-cong-nghe-thong-tin-tphcm',
    name: 'Trường Đại học Công nghệ Thông tin - ĐHQG TP.HCM',
    abbreviation: 'UIT',
    region: 'TP. Hồ Chí Minh',
    address: 'Khu phố 6, Linh Trung, TP. Thủ Đức, TP.HCM',
    lat: 10.8702,
    lng: 106.8032,
  },
  {
    slug: 'dh-quoc-te-tphcm',
    name: 'Trường Đại học Quốc tế - ĐHQG TP.HCM',
    abbreviation: 'IU HCM',
    region: 'TP. Hồ Chí Minh',
    address: 'Khu phố 6, Linh Trung, TP. Thủ Đức, TP.HCM',
    lat: 10.8778,
    lng: 106.8016,
  },
  {
    slug: 'dh-kinh-te-tphcm',
    name: 'Đại học Kinh tế TP. Hồ Chí Minh',
    abbreviation: 'UEH',
    region: 'TP. Hồ Chí Minh',
    address: '59C Nguyễn Đình Chiểu, Phường 6, Quận 3, TP.HCM',
    lat: 10.7828,
    lng: 106.6958,
  },
  {
    slug: 'dh-ton-duc-thang',
    name: 'Trường Đại học Tôn Đức Thắng',
    abbreviation: 'TDTU',
    region: 'TP. Hồ Chí Minh',
    address: '19 Nguyễn Hữu Thọ, Tân Phong, Quận 7, TP.HCM',
    lat: 10.7326,
    lng: 106.6992,
  },
  {
    slug: 'dh-su-pham-ky-thuat-tphcm',
    name: 'Trường Đại học Sư phạm Kỹ thuật TP.HCM',
    abbreviation: 'HCMUTE',
    region: 'TP. Hồ Chí Minh',
    address: '1 Võ Văn Ngân, Linh Chiểu, TP. Thủ Đức, TP.HCM',
    lat: 10.8507,
    lng: 106.7719,
  },
  {
    slug: 'dh-y-duoc-tphcm',
    name: 'Đại học Y Dược TP. Hồ Chí Minh',
    abbreviation: 'UMP HCM',
    region: 'TP. Hồ Chí Minh',
    address: '217 Hồng Bàng, Phường 11, Quận 5, TP.HCM',
    lat: 10.7551,
    lng: 106.6599,
  },
  {
    slug: 'dh-y-khoa-pham-ngoc-thach',
    name: 'Trường Đại học Y khoa Phạm Ngọc Thạch',
    abbreviation: 'PNTU',
    region: 'TP. Hồ Chí Minh',
    address: '2 Dương Quang Trung, Phường 12, Quận 10, TP.HCM',
    lat: 10.7733,
    lng: 106.6669,
  },
  {
    slug: 'dh-su-pham-tphcm',
    name: 'Trường Đại học Sư phạm TP. Hồ Chí Minh',
    abbreviation: 'HCMUE',
    region: 'TP. Hồ Chí Minh',
    address: '280 An Dương Vương, Phường 4, Quận 5, TP.HCM',
    lat: 10.7601,
    lng: 106.6823,
  },
  {
    slug: 'dh-sai-gon',
    name: 'Trường Đại học Sài Gòn',
    abbreviation: 'SGU',
    region: 'TP. Hồ Chí Minh',
    address: '273 An Dương Vương, Phường 3, Quận 5, TP.HCM',
    lat: 10.7597,
    lng: 106.6811,
  },
  {
    slug: 'dh-luat-tphcm',
    name: 'Trường Đại học Luật TP. Hồ Chí Minh',
    abbreviation: 'ULAW',
    region: 'TP. Hồ Chí Minh',
    address: '2 Nguyễn Tất Thành, Phường 12, Quận 4, TP.HCM',
    lat: 10.7671,
    lng: 106.7077,
  },
  {
    slug: 'dh-ngoai-thuong-cs2',
    name: 'Trường Đại học Ngoại thương - Cơ sở 2',
    abbreviation: 'FTU2',
    region: 'TP. Hồ Chí Minh',
    address: '15 Đường D5, Phường 25, Bình Thạnh, TP.HCM',
    lat: 10.8037,
    lng: 106.7144,
  },
  {
    slug: 'dh-ngan-hang-tphcm',
    name: 'Trường Đại học Ngân hàng TP. Hồ Chí Minh',
    abbreviation: 'HUB',
    region: 'TP. Hồ Chí Minh',
    address: '36 Tôn Thất Đạm, Quận 1 / 56 Hoàng Diệu 2, Thủ Đức, TP.HCM',
    lat: 10.8561,
    lng: 106.7645,
  },
  {
    slug: 'dh-tai-chinh-marketing',
    name: 'Trường Đại học Tài chính - Marketing',
    abbreviation: 'UFM',
    region: 'TP. Hồ Chí Minh',
    address: '778 Nguyễn Kiệm, Phường 4, Phú Nhuận, TP.HCM',
    lat: 10.8144,
    lng: 106.6778,
  },
  {
    slug: 'dh-mo-tphcm',
    name: 'Trường Đại học Mở TP. Hồ Chí Minh',
    abbreviation: 'OU HCM',
    region: 'TP. Hồ Chí Minh',
    address: '97 Võ Văn Tần, Phường 6, Quận 3, TP.HCM',
    lat: 10.7766,
    lng: 106.6912,
  },
  {
    slug: 'dh-nong-lam-tphcm',
    name: 'Trường Đại học Nông Lâm TP. Hồ Chí Minh',
    abbreviation: 'NLU',
    region: 'TP. Hồ Chí Minh',
    address: 'Khu phố 6, Linh Trung, TP. Thủ Đức, TP.HCM',
    lat: 10.8711,
    lng: 106.7915,
  },
  {
    slug: 'dh-cong-nghiep-tphcm',
    name: 'Trường Đại học Công nghiệp TP. Hồ Chí Minh',
    abbreviation: 'IUH',
    region: 'TP. Hồ Chí Minh',
    address: '12 Nguyễn Văn Bảo, Phường 4, Gò Vấp, TP.HCM',
    lat: 10.8222,
    lng: 106.6875,
  },
  {
    slug: 'dh-cong-thuong-tphcm',
    name: 'Trường Đại học Công Thương TP. Hồ Chí Minh',
    abbreviation: 'HUIT',
    region: 'TP. Hồ Chí Minh',
    address: '140 Lê Trọng Tấn, Tây Thạnh, Tân Phú, TP.HCM',
    lat: 10.8063,
    lng: 106.6287,
  },
  {
    slug: 'dh-kien-truc-tphcm',
    name: 'Trường Đại học Kiến trúc TP. Hồ Chí Minh',
    abbreviation: 'UAH',
    region: 'TP. Hồ Chí Minh',
    address: '196 Pasteur, Phường 6, Quận 3, TP.HCM',
    lat: 10.7825,
    lng: 106.6942,
  },
  {
    slug: 'dh-van-lang',
    name: 'Trường Đại học Văn Lang',
    abbreviation: 'VLU',
    region: 'TP. Hồ Chí Minh',
    address: '69/68 Đặng Thùy Trâm, Phường 13, Bình Thạnh, TP.HCM',
    lat: 10.8285,
    lng: 106.7028,
  },
  {
    slug: 'dh-hoa-sen',
    name: 'Trường Đại học Hoa Sen',
    abbreviation: 'HSU',
    region: 'TP. Hồ Chí Minh',
    address: '8 Nguyễn Văn Tráng, Bến Thành, Quận 1, TP.HCM',
    lat: 10.7712,
    lng: 106.6922,
  },
  {
    slug: 'dh-cong-nghe-tphcm-hutech',
    name: 'Trường Đại học Công nghệ TP.HCM',
    abbreviation: 'HUTECH',
    region: 'TP. Hồ Chí Minh',
    address: '475A Điện Biên Phủ, Phường 25, Bình Thạnh, TP.HCM',
    lat: 10.8016,
    lng: 106.7145,
  },
  {
    slug: 'dh-kinh-te-tai-chinh-tphcm',
    name: 'Trường Đại học Kinh tế - Tài chính TP.HCM',
    abbreviation: 'UEF',
    region: 'TP. Hồ Chí Minh',
    address: '141-145 Điện Biên Phủ, Phường 15, Bình Thạnh, TP.HCM',
    lat: 10.7963,
    lng: 106.7042,
  },
  {
    slug: 'dh-quoc-te-hong-bang',
    name: 'Trường Đại học Quốc tế Hồng Bàng',
    abbreviation: 'HIU',
    region: 'TP. Hồ Chí Minh',
    address: '215 Điện Biên Phủ, Phường 15, Bình Thạnh, TP.HCM',
    lat: 10.7981,
    lng: 106.7088,
  },
  {
    slug: 'dh-fpt-tphcm',
    name: 'Trường Đại học FPT TP. Hồ Chí Minh',
    abbreviation: 'FPT HCM',
    region: 'TP. Hồ Chí Minh',
    address: 'Đường D1, Khu Công nghệ cao, Long Thạnh Mỹ, TP. Thủ Đức, TP.HCM',
    lat: 10.8557,
    lng: 106.8087,
  },

  // ── HÀ NỘI ──
  {
    slug: 'dhqg-ha-noi',
    name: 'Đại học Quốc gia Hà Nội',
    abbreviation: 'VNU HN',
    region: 'Hà Nội',
    address: '144 Xuân Thủy, Dịch Vọng Hậu, Cầu Giấy, Hà Nội',
    lat: 21.0373,
    lng: 105.7828,
  },
  {
    slug: 'dh-bach-khoa-ha-noi',
    name: 'Đại học Bách Khoa Hà Nội',
    abbreviation: 'HUST',
    region: 'Hà Nội',
    address: 'Số 1 Đại Cồ Việt, Bách Khoa, Hai Bà Trưng, Hà Nội',
    lat: 21.0056,
    lng: 105.8433,
  },
  {
    slug: 'dh-kinh-te-quoc-dan',
    name: 'Trường Đại học Kinh tế Quốc dân',
    abbreviation: 'NEU',
    region: 'Hà Nội',
    address: '207 Giải Phóng, Đồng Tâm, Hai Bà Trưng, Hà Nội',
    lat: 20.9996,
    lng: 105.8427,
  },
  {
    slug: 'dh-ngoai-thuong-hn',
    name: 'Trường Đại học Ngoại thương',
    abbreviation: 'FTU',
    region: 'Hà Nội',
    address: '91 Chùa Láng, Láng Thượng, Đống Đa, Hà Nội',
    lat: 21.0232,
    lng: 105.8049,
  },
  {
    slug: 'hoc-vien-tai-chinh',
    name: 'Học viện Tài chính',
    abbreviation: 'AOF',
    region: 'Hà Nội',
    address: '58 Lê Văn Hiến, Đức Thắng, Bắc Từ Liêm, Hà Nội',
    lat: 21.0772,
    lng: 105.7744,
  },
  {
    slug: 'hoc-vien-ngan-hang',
    name: 'Học viện Ngân hàng',
    abbreviation: 'BA',
    region: 'Hà Nội',
    address: '12 Chùa Bộc, Quang Trung, Đống Đa, Hà Nội',
    lat: 21.0084,
    lng: 105.8285,
  },
  {
    slug: 'dh-thuong-mai',
    name: 'Trường Đại học Thương mại',
    abbreviation: 'TMU',
    region: 'Hà Nội',
    address: '79 Hồ Tùng Mậu, Mai Dịch, Cầu Giấy, Hà Nội',
    lat: 21.0366,
    lng: 105.7742,
  },
  {
    slug: 'dh-xay-dung-ha-noi',
    name: 'Trường Đại học Xây dựng Hà Nội',
    abbreviation: 'HUCE',
    region: 'Hà Nội',
    address: '55 Giải Phóng, Đồng Tâm, Hai Bà Trưng, Hà Nội',
    lat: 21.0039,
    lng: 105.8419,
  },
  {
    slug: 'dh-giao-thong-van-tai',
    name: 'Trường Đại học Giao thông Vận tải',
    abbreviation: 'UTC',
    region: 'Hà Nội',
    address: 'Số 3 Cầu Giấy, Láng Thượng, Đống Đa, Hà Nội',
    lat: 21.0289,
    lng: 105.8037,
  },
  {
    slug: 'dh-y-ha-noi',
    name: 'Trường Đại học Y Hà Nội',
    abbreviation: 'HMU',
    region: 'Hà Nội',
    address: 'Số 1 Tôn Thất Tùng, Trung Tự, Đống Đa, Hà Nội',
    lat: 21.0028,
    lng: 105.8317,
  },
  {
    slug: 'dh-duoc-ha-noi',
    name: 'Trường Đại học Dược Hà Nội',
    abbreviation: 'HUP',
    region: 'Hà Nội',
    address: '13-15 Lê Thánh Tông, Phan Chu Trinh, Hoàn Kiếm, Hà Nội',
    lat: 21.0219,
    lng: 105.8569,
  },
  {
    slug: 'hoc-vien-cong-nghe-buu-chinh-vien-thong',
    name: 'Học viện Công nghệ Bưu chính Viễn thông',
    abbreviation: 'PTIT',
    region: 'Hà Nội',
    address: 'Km10 Đường Nguyễn Trãi, Hà Đông, Hà Nội',
    lat: 20.9808,
    lng: 105.7876,
  },
  {
    slug: 'dh-su-pham-ha-noi',
    name: 'Trường Đại học Sư phạm Hà Nội',
    abbreviation: 'HNUE',
    region: 'Hà Nội',
    address: '136 Xuân Thủy, Dịch Vọng Hậu, Cầu Giấy, Hà Nội',
    lat: 21.0368,
    lng: 105.7842,
  },
  {
    slug: 'dh-ha-noi',
    name: 'Trường Đại học Hà Nội',
    abbreviation: 'HANU',
    region: 'Hà Nội',
    address: 'Km 9 Đường Nguyễn Trãi, Trung Văn, Nam Từ Liêm, Hà Nội',
    lat: 20.9912,
    lng: 105.7958,
  },
  {
    slug: 'dh-cong-nghiep-ha-noi',
    name: 'Trường Đại học Công nghiệp Hà Nội',
    abbreviation: 'HaUI',
    region: 'Hà Nội',
    address: '298 Cầu Diễn, Minh Khai, Bắc Từ Liêm, Hà Nội',
    lat: 21.0537,
    lng: 105.7351,
  },
  {
    slug: 'hoc-vien-bao-chi-tuyen-truyen',
    name: 'Học viện Báo chí và Tuyên truyền',
    abbreviation: 'AJC',
    region: 'Hà Nội',
    address: '36 Xuân Thủy, Dịch Vọng Hậu, Cầu Giấy, Hà Nội',
    lat: 21.0363,
    lng: 105.7892,
  },
  {
    slug: 'hoc-vien-ngoai-giao',
    name: 'Học viện Ngoại giao',
    abbreviation: 'DAV',
    region: 'Hà Nội',
    address: '69 Chùa Láng, Láng Thượng, Đống Đa, Hà Nội',
    lat: 21.0227,
    lng: 105.8071,
  },
  {
    slug: 'dh-luat-ha-noi',
    name: 'Trường Đại học Luật Hà Nội',
    abbreviation: 'HLU',
    region: 'Hà Nội',
    address: '87 Nguyễn Chí Thanh, Láng Hạ, Đống Đa, Hà Nội',
    lat: 21.0189,
    lng: 105.8119,
  },
  {
    slug: 'dh-kien-truc-ha-noi',
    name: 'Trường Đại học Kiến trúc Hà Nội',
    abbreviation: 'HAU',
    region: 'Hà Nội',
    address: 'Km 10 Đường Nguyễn Trãi, Văn Quán, Hà Đông, Hà Nội',
    lat: 20.9822,
    lng: 105.7891,
  },
  {
    slug: 'dh-thuy-loi',
    name: 'Trường Đại học Thủy lợi',
    abbreviation: 'TLU',
    region: 'Hà Nội',
    address: '175 Tây Sơn, Trung Liệt, Đống Đa, Hà Nội',
    lat: 21.0076,
    lng: 105.8242,
  },
  {
    slug: 'dh-mo-dia-chat',
    name: 'Trường Đại học Mỏ - Địa chất',
    abbreviation: 'HUMG',
    region: 'Hà Nội',
    address: 'Số 18 Phố Viên, Đức Thắng, Bắc Từ Liêm, Hà Nội',
    lat: 21.0725,
    lng: 105.7738,
  },
  {
    slug: 'dh-thang-long',
    name: 'Trường Đại học Thăng Long',
    abbreviation: 'TLU HN',
    region: 'Hà Nội',
    address: 'Đường Nghiêm Xuân Yêm, Đại Kim, Hoàng Mai, Hà Nội',
    lat: 20.9765,
    lng: 105.8157,
  },
  {
    slug: 'dh-phenikaa',
    name: 'Trường Đại học Phenikaa',
    abbreviation: 'Phenikaa',
    region: 'Hà Nội',
    address: 'Đường Tố Hữu, Yên Nghĩa, Hà Đông, Hà Nội',
    lat: 20.9635,
    lng: 105.7483,
  },
  {
    slug: 'dh-fpt-ha-noi',
    name: 'Trường Đại học FPT Hà Nội',
    abbreviation: 'FPT HN',
    region: 'Hà Nội',
    address: 'Khu CNC Hòa Lạc, Km 29 Đại lộ Thăng Long, Thạch Thất, Hà Nội',
    lat: 21.0131,
    lng: 105.5262,
  },
  {
    slug: 'hoc-vien-nong-nghiep-vn',
    name: 'Học viện Nông nghiệp Việt Nam',
    abbreviation: 'VNUA',
    region: 'Hà Nội',
    address: 'Thị trấn Trâu Quỳ, Gia Lâm, Hà Nội',
    lat: 21.0051,
    lng: 105.9328,
  },

  // ── ĐÀ NẴNG & MIỀN TRUNG ──
  {
    slug: 'dh-bach-khoa-da-nang',
    name: 'Trường Đại học Bách Khoa - ĐH Đà Nẵng',
    abbreviation: 'DUT Đà Nẵng',
    region: 'Đà Nẵng & Miền Trung',
    address: '54 Nguyễn Lương Bằng, Hòa Khánh Bắc, Liên Chiểu, Đà Nẵng',
    lat: 16.0738,
    lng: 108.1499,
  },
  {
    slug: 'dh-kinh-te-da-nang',
    name: 'Trường Đại học Kinh tế - ĐH Đà Nẵng',
    abbreviation: 'DUE Đà Nẵng',
    region: 'Đà Nẵng & Miền Trung',
    address: '71 Ngũ Hành Sơn, Bắc Mỹ An, Ngũ Hành Sơn, Đà Nẵng',
    lat: 16.0506,
    lng: 108.2415,
  },
  {
    slug: 'dh-su-pham-da-nang',
    name: 'Trường Đại học Sư phạm - ĐH Đà Nẵng',
    abbreviation: 'UED Đà Nẵng',
    region: 'Đà Nẵng & Miền Trung',
    address: '459 Tôn Đức Thắng, Hòa Khánh Nam, Liên Chiểu, Đà Nẵng',
    lat: 16.0612,
    lng: 108.1584,
  },
  {
    slug: 'dh-ngoai-ngu-da-nang',
    name: 'Trường Đại học Ngoại ngữ - ĐH Đà Nẵng',
    abbreviation: 'UFL Đà Nẵng',
    region: 'Đà Nẵng & Miền Trung',
    address: '131 Lương Nhữ Hộc, Khuê Trung, Cẩm Lệ, Đà Nẵng',
    lat: 16.0354,
    lng: 108.2107,
  },
  {
    slug: 'dh-su-pham-ky-thuat-da-nang',
    name: 'Trường Đại học Sư phạm Kỹ thuật - ĐH Đà Nẵng',
    abbreviation: 'UTE Đà Nẵng',
    region: 'Đà Nẵng & Miền Trung',
    address: '48 Cao Thắng, Thanh Bình, Hải Châu, Đà Nẵng',
    lat: 16.0782,
    lng: 108.2144,
  },
  {
    slug: 'dh-duy-tan',
    name: 'Trường Đại học Duy Tân',
    abbreviation: 'DTU',
    region: 'Đà Nẵng & Miền Trung',
    address: '254 Nguyễn Văn Linh, Thạc Gián, Thanh Khê, Đà Nẵng',
    lat: 16.0617,
    lng: 108.2081,
  },
  {
    slug: 'dh-fpt-da-nang',
    name: 'Trường Đại học FPT Đà Nẵng',
    abbreviation: 'FPT ĐN',
    region: 'Đà Nẵng & Miền Trung',
    address: 'Khu Đô thị FPT City, Hòa Hải, Ngũ Hành Sơn, Đà Nẵng',
    lat: 15.9863,
    lng: 108.2612,
  },
  {
    slug: 'dh-y-duoc-hue',
    name: 'Trường Đại học Y - Dược, Đại học Huế',
    abbreviation: 'UMP Huế',
    region: 'Đà Nẵng & Miền Trung',
    address: '06 Ngô Quyền, Vĩnh Ninh, TP. Huế, Thừa Thiên Huế',
    lat: 16.4632,
    lng: 107.5855,
  },
  {
    slug: 'dh-kinh-te-hue',
    name: 'Trường Đại học Kinh tế, Đại học Huế',
    abbreviation: 'HCE Huế',
    region: 'Đà Nẵng & Miền Trung',
    address: '99 Hồ Đắc Di, An Cựu, TP. Huế, Thừa Thiên Huế',
    lat: 16.4428,
    lng: 107.5991,
  },
  {
    slug: 'dh-khoa-hoc-hue',
    name: 'Trường Đại học Khoa học, Đại học Huế',
    abbreviation: 'HUSC Huế',
    region: 'Đà Nẵng & Miền Trung',
    address: '77 Nguyễn Huệ, Phú Nhuận, TP. Huế, Thừa Thiên Huế',
    lat: 16.4571,
    lng: 107.5898,
  },
  {
    slug: 'dh-nha-trang',
    name: 'Trường Đại học Nha Trang',
    abbreviation: 'NTU',
    region: 'Đà Nẵng & Miền Trung',
    address: '02 Nguyễn Đình Chiểu, Vĩnh Thọ, TP. Nha Trang, Khánh Hòa',
    lat: 12.2685,
    lng: 109.2023,
  },
  {
    slug: 'dh-quy-nhon',
    name: 'Trường Đại học Quy Nhơn',
    abbreviation: 'QNU',
    region: 'Đà Nẵng & Miền Trung',
    address: '170 An Dương Vương, Nguyễn Văn Cừ, TP. Quy Nhơn, Bình Định',
    lat: 13.7589,
    lng: 109.2173,
  },
  {
    slug: 'dh-da-lat',
    name: 'Trường Đại học Đà Lạt',
    abbreviation: 'DLU',
    region: 'Đà Nẵng & Miền Trung',
    address: '01 Phù Đổng Thiên Vương, Phường 8, TP. Đà Lạt, Lâm Đồng',
    lat: 11.9546,
    lng: 108.4448,
  },
  {
    slug: 'dh-tay-nguyen',
    name: 'Trường Đại học Tây Nguyên',
    abbreviation: 'TNU Tây Nguyên',
    region: 'Đà Nẵng & Miền Trung',
    address: '567 Lê Duẩn, Ea Tam, TP. Buôn Ma Thuột, Đắk Lắk',
    lat: 12.6568,
    lng: 108.0526,
  },

  // ── CẦN THƠ & MIỀN TÂY ──
  {
    slug: 'dh-can-tho',
    name: 'Trường Đại học Cần Thơ',
    abbreviation: 'CTU Cần Thơ',
    region: 'Cần Thơ & Miền Tây',
    address: 'Khu II, Đường 3/2, Xuân Khánh, Ninh Kiều, Cần Thơ',
    lat: 10.0312,
    lng: 105.7691,
  },
  {
    slug: 'dh-y-duoc-can-tho',
    name: 'Trường Đại học Y Dược Cần Thơ',
    abbreviation: 'CTUMP',
    region: 'Cần Thơ & Miền Tây',
    address: '179 Nguyễn Văn Cừ, An Khánh, Ninh Kiều, Cần Thơ',
    lat: 10.0347,
    lng: 105.7538,
  },
  {
    slug: 'dh-ky-thuat-cong-nghe-can-tho',
    name: 'Trường ĐH Kỹ thuật - Công nghệ Cần Thơ',
    abbreviation: 'CTUT',
    region: 'Cần Thơ & Miền Tây',
    address: '256 Nguyễn Văn Cừ, An Hòa, Ninh Kiều, Cần Thơ',
    lat: 10.0465,
    lng: 105.7674,
  },
  {
    slug: 'dh-nam-can-tho',
    name: 'Trường Đại học Nam Cần Thơ',
    abbreviation: 'DNC',
    region: 'Cần Thơ & Miền Tây',
    address: '168 Nguyễn Văn Cừ nối dài, An Bình, Ninh Kiều, Cần Thơ',
    lat: 10.0076,
    lng: 105.7332,
  },
  {
    slug: 'dh-fpt-can-tho',
    name: 'Trường Đại học FPT Cần Thơ',
    abbreviation: 'FPT Cần Thơ',
    region: 'Cần Thơ & Miền Tây',
    address: 'Số 600 đường Nguyễn Văn Cừ nối dài, An Bình, Ninh Kiều, Cần Thơ',
    lat: 10.0125,
    lng: 105.7314,
  },
  {
    slug: 'dh-an-giang',
    name: 'Trường Đại học An Giang - ĐHQG TP.HCM',
    abbreviation: 'AGU',
    region: 'Cần Thơ & Miền Tây',
    address: '18 Ung Văn Khiêm, Đông Xuyên, TP. Long Xuyên, An Giang',
    lat: 10.3734,
    lng: 105.4346,
  },
  {
    slug: 'dh-dong-thap',
    name: 'Trường Đại học Đồng Tháp',
    abbreviation: 'DThU',
    region: 'Cần Thơ & Miền Tây',
    address: '783 Phạm Hữu Lầu, Phường 6, TP. Cao Lãnh, Đồng Tháp',
    lat: 10.4502,
    lng: 105.6421,
  },
  {
    slug: 'dh-tra-vinh',
    name: 'Trường Đại học Trà Vinh',
    abbreviation: 'TVU',
    region: 'Cần Thơ & Miền Tây',
    address: '126 Nguyễn Thiện Thành, Khóm 4, Phường 5, TP. Trà Vinh',
    lat: 9.9234,
    lng: 106.3456,
  },

  // ── MIỀN BẮC KHÁC ──
  {
    slug: 'dh-thai-nguyen',
    name: 'Đại học Thái Nguyên',
    abbreviation: 'TNU Thái Nguyên',
    region: 'Miền Bắc khác',
    address: 'Phường Tân Thịnh, TP. Thái Nguyên, Thái Nguyên',
    lat: 21.5849,
    lng: 105.8118,
  },
  {
    slug: 'dh-hang-hai-viet-nam',
    name: 'Trường Đại học Hàng hải Việt Nam',
    abbreviation: 'VMU Hải Phòng',
    region: 'Miền Bắc khác',
    address: '484 Lạch Tray, Kênh Dương, Lê Chân, Hải Phòng',
    lat: 20.8351,
    lng: 106.6946,
  },
  {
    slug: 'dh-y-duoc-hai-phong',
    name: 'Trường Đại học Y Dược Hải Phòng',
    abbreviation: 'HPMU',
    region: 'Miền Bắc khác',
    address: '722 Ngô Gia Tự, Đằng Lâm, Hải An, Hải Phòng',
    lat: 20.8389,
    lng: 106.7112,
  },
  {
    slug: 'dh-hai-phong',
    name: 'Trường Đại học Hải Phòng',
    abbreviation: 'DHHP',
    region: 'Miền Bắc khác',
    address: '171 Phan Đăng Lưu, Kiến An, Hải Phòng',
    lat: 20.8035,
    lng: 106.6348,
  },
  {
    slug: 'dh-ha-long',
    name: 'Trường Đại học Hạ Long',
    abbreviation: 'UHL Quảng Ninh',
    region: 'Miền Bắc khác',
    address: '258 Bạch Đằng, Nam Khê, TP. Uông Bí, Quảng Ninh',
    lat: 21.0336,
    lng: 106.7912,
  },
];
